version: '2'
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
      GAMMA_EMAIL: gustav.engsmyre@gmail.com
      GAMMA_EMAIL_PASSWORD: glmxmanbpehkvilw
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
