version: '2'
volumes:
  node_modules:
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - 5432:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  frontend:
    build:
      context: ./frontend/
      dockerfile: dev.dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/usr/src/app
      - node_modules:/usr/src/app/node_modules

  backend:
    build:
      context: ./backend/
      dockerfile: dev.dockerfile
    ports:
      - 8081:8081
    environment:
      GAMMA_PORT: 8081
    volumes:
      - ./backend:/app
