spring:
  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:example}
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/postgres
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defazults: false
  resources:

server:
  port: ${SERVER_PORT:8081}
  servlet:
    context-path: /api

logging:
  level:
    root: INFO
    org:
      springframework:
        web: INFO
      hibernate: INFO

security:
  jwt:
    token:
      secret-key: xJqKgDuIikgjkvOXI71j8LKkBlKg3bdr7/WYN6Q0uDs= # This is only for Development, should also be a secret one for Production
      expire-length: 2592000000 #One Month. Subject to change.
      issuer: http://localhost:8081

application:
  frontend-client-details:
    client-id: ${FRONTEND_CLIENT_ID:7hAdUEtMo4MgFnA7ZoZ41ohTe1NNRoJmjL67Gf0NIrrBnauyhc}
    client-secret: ${FRONTEND_CLIENT_SECRET:LBoxmzohQOSRCz99uBhS0IjLglxUOaLRXJxIC8iWuHTWYCLLqo}
    redirect-uri: ${FRONTEND_REDIRECT_URI:http://localhost:3000/login}
  standard-admin-account:
    password: ${ADMIN_PASSWORD:password}
  gotify:
    key: "key"                  # This is not needed, but application crashes since it looks for these values.
    url: "gotify.chalmers.it"
  allowed-origin: ${CORS_ALLOWED_ORIGIN:http://localhost:3000}
  auth:
    accessTokenValidityTime: 3600
    autoApprove: true
    refreshTokenValidityTime: 500000000
  imageit:
    url: ${IMAGEIT_URL:http://localhost:5000}
    apiKey: ${IMAGEIT_API_KEY:secret}