spring:
  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:example}
    url: jdbc:postgresql://${DB_HOST:localhost}:5432/postgres
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL29Dialect
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        temp:
          #http://vkuzel.blogspot.se/2016/03/spring-boot-jpa-hibernate-atomikos.html
          use_jdbc_metadata_defaults: false
    generate-ddl: true


server:
  port: ${SERVER_PORT:8081}

logging:
  level:
    root: WARN
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR

security:
  jwt:
    token:
      secret-key: ${JWT_SECRET_KEY:jwtkey} # This is only for Development, should also be a secret one for Production
      expire-length: ${JWT_EXPIRE_LENGTH:2592000000} #One Month. Subject to change.
      issuer: CTHIT

gotify:
  key: ${GOTIFY_KEY}
  url: ${GOTIFY_URL}

application:
  standard-admin-account:
    password: ${ADMIN_PASSWORD:password}