spring:
  datasource:
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:example}
    url: jdbc:postgresql://localhost:5432/postgres
  output:
    ansi:
      enabled: ALWAYS
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        temp:
          #http://vkuzel.blogspot.se/2016/03/spring-boot-jpa-hibernate-atomikos.html
          use_jdbc_metadata_defaults: false

server:
  port: ${GAMMA_PORT:8081}

logging:
  level:
    root: WARN
    org:
      springframework:
        web: DEBUG
      hibernate: ERROR

security:
  jwt:
    token:
      secret-key: xJqKgDuIikgjkvOXI71j8LKkBlKg3bdr7/WYN6Q0uDs= # This is only for Development, should also be a secret one for Production
      expire-length: 2592000000 #One Month. Subject to change.
      issuer: CTHIT